version: '1.0'
services:
  api-container:
    container_name: basic-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - common-network
    depends_on:
      - mysql-container


  mysql-container:
    restart: always
    image: mysql:8.0.3
    container_name: mysql
    ports:
      - 3306:3306
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: bGl5YW5n
      TZ: Asia/Shanghai
    volumes:
      - mysql-data:/var/lib/mysql
#      - /root/docker/mysql_home/conf:/etc/mysql/conf.d
#      - /root/docker/mysql_home/log:/var/log/mysql
    networks:
      - common-network
volumes:
  mysql-data:
networks:
  common-network:
    driver: bridge
