version: '1.0'
services:
  basic-api:
    container_name: basic-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - common-network

networks:
  common-network:
    driver: bridge