export enum ENV {
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_TYPE = 'MYSQL_TYPE',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
}

export enum ENV_JWT {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRED = 'JWT_EXPIRED',
  JWT_EXPIRED_REFRESH = 'JWT_EXPIRED_REFRESH',
}
